const tempReviewsData = [
  {
    name: "John Doe",
    rating: 4,
    comment:
      "Great product! Highly recommended. Quality exceeded expectations. Will buy again.",
    avatarUrl: "avatar-1.jpg",
    postedOn: "15/02/2022",
  },
  {
    name: "Jane Smith",
    rating: 5,
    comment:
      "Excellent service and fast delivery. Impressed with the packaging. A delightful shopping experience.",
    avatarUrl: "avatar-2.jpg",
    postedOn: "10/02/2022",
  },
  {
    name: "Bob Johnson",
    rating: 4,
    comment:
      "Good product, could be better. Sturdy build, minor improvements possible. Overall satisfied.",
    avatarUrl: "avatar-3.jpg",
    postedOn: "25/05/2022",
  },
  {
    name: "Alice Williams",
    rating: 5,
    comment:
      "Absolutely fantastic! Love it. Exceeded my expectations. Beautiful design and excellent performance.",
    avatarUrl: "avatar-4.jpg",
    postedOn: "19/02/2023",
  },
  {
    name: "Charlie Brown",
    rating: 4,
    comment:
      "Good value for the price. Reliable performance. Recommended for budget-conscious buyers.",
    avatarUrl: "avatar-5.jpg",
    postedOn: "13/08/2023",
  },
];

const tempProductsData = [
  {
    id: 1,
    name: "Sapphire Elegance Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 19.99,
    discountedPrice: 16.99,
    description: [
      "Premium sapphire blue fabric for an elegant look.",
      "Ultra-soft lining for maximum comfort.",
      "Adjustable wrist strap for a customized fit.",
      "Durable stitching ensures long-lasting quality.",
      "Versatile design suitable for both casual and formal occasions.",
      "Offers protection against cold weather without compromising style.",
      "Easy to clean and maintain.",
      "Available in multiple sizes to suit every hand.",
      "Great gift idea for fashion-conscious individuals.",
      "Limited-time discount – grab yours now!",
    ],
  },
  {
    id: 2,
    name: "Velvet Touch Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 39.99,
    discountedPrice: 33.99,
    description: [
      "Luxurious velvet material for a premium touch.",
      "Thermal insulation to keep your hands warm in cold weather.",
      "Stylish and trendy design for a fashionable look.",
      "Precision stitching for a durable and refined finish.",
      "Elastic cuff for a snug fit around the wrist.",
      "Available in multiple colors to match your wardrobe.",
      "Ideal for both formal events and everyday wear.",
      "Easy to pair with various outfits.",
      "Discounted price for a limited time!",
      "Perfect holiday gift for loved ones.",
    ],
  },
  {
    id: 3,
    name: "Radiant Charm Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 49.99,
    discountedPrice: 42.49,
    description: [
      "Charming design with radiant patterns.",
      "Soft and cozy interior for all-day comfort.",
      "Enhanced grip for practical use in various activities.",
      "Quality materials for durability and longevity.",
      "Fashionable accessory to elevate your style.",
      "Versatile enough for both casual and formal occasions.",
      "Unique gift option for special occasions.",
      "Discounted price for a limited period.",
      "Available in multiple sizes for a perfect fit.",
      "Order now to experience the charm!",
    ],
  },
  {
    id: 4,
    name: "Midnight Mirage Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 59.99,
    discountedPrice: 50.99,
    description: [
      "Mysterious midnight black color for a captivating look.",
      "Innovative mirage pattern adds a touch of intrigue.",
      "High-quality construction for durability.",
      "Comfortable fit for extended wear.",
      "Suitable for various outdoor activities.",
      "Designed to protect against cold and wind.",
      "Easy to clean and maintain.",
      "Limited-time discount – don't miss out!",
      "Available in a range of sizes.",
      "Order now and embrace the midnight allure!",
    ],
  },
  {
    id: 5,
    name: "Whispering Breeze Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 69.99,
    discountedPrice: 59.49,
    description: [
      "Gentle breeze-inspired design for a serene look.",
      "Soft and breathable fabric for all-day comfort.",
      "Subtle color palette adds a touch of elegance.",
      "Ideal for both autumn and winter seasons.",
      "Precision stitching for durability.",
      "Versatile style suitable for various occasions.",
      "Available in multiple sizes for a perfect fit.",
      "Discounted price for a limited time!",
      "A perfect gift for those who love nature.",
      "Embrace the whispering breeze – order now!",
    ],
  },
  {
    id: 6,
    name: "Winter Bliss Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 29.99,
    discountedPrice: 25.49,
    description: [
      "Keep your hands warm and cozy in these winter gloves.",
      "Soft and insulated material for cold weather protection.",
      "Stylish design adds a touch of elegance.",
      "Comfortable fit for everyday wear.",
      "Perfect for winter outings and activities.",
      "Easy to clean and maintain.",
      "Available in various sizes for a customized fit.",
      "Discounted price for a limited time!",
      "Experience the bliss of winter with these gloves.",
      "Order now and stay warm in style!",
    ],
  },
  {
    id: 7,
    name: "Velocity Sprint Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 34.99,
    discountedPrice: 29.74,
    description: [
      "Perfect for sports activities, providing a comfortable grip.",
      "Designed for high-speed movements and agility.",
      "Breathable material to keep hands cool during workouts.",
      "Secure fit with adjustable straps.",
      "Durable construction for long-lasting use.",
      "Versatile design suitable for various sports.",
      "Enhance your performance with these sprint gloves.",
      "Discounted price for fitness enthusiasts.",
      "Available in different sizes for a perfect fit.",
      "Order now and sprint towards your fitness goals!",
    ],
  },
  {
    id: 8,
    name: "Mystic Aura Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 49.99,
    discountedPrice: 42.49,
    description: [
      "Stay stylish with these elegant leather gloves.",
      "Mystic aura pattern adds a touch of intrigue.",
      "Soft and comfortable interior for extended wear.",
      "Versatile design suitable for various occasions.",
      "Premium leather construction for durability.",
      "Ideal for both casual and formal outfits.",
      "Available in multiple sizes for a customized fit.",
      "Discounted price for a limited time!",
      "Make a statement with the mystic aura – order now!",
      "A perfect gift for those who appreciate luxury.",
    ],
  },
  {
    id: 9,
    name: "Guardian Shield Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 39.99,
    discountedPrice: 33.99,
    description: [
      "Designed for safety at work, providing protection and comfort.",
      "Reinforced knuckles for added protection.",
      "Durable and resistant to wear and tear.",
      "Secure fit with adjustable wrist strap.",
      "Ideal for various industrial and manual tasks.",
      "Comfortable enough for extended wear.",
      "Easy to clean and maintain.",
      "Available in different sizes for a perfect fit.",
      "Discounted price for a limited time!",
      "Protect your hands with these reliable gloves.",
    ],
  },
  {
    id: 10,
    name: "Digital Harmony Gloves",
    imageSrc: [
      "product-1.png",
      "product-2.png",
      "product-3.png",
      "product-4.png",
      "product-5.png",
    ],
    price: 24.99,
    discountedPrice: 21.24,
    description: [
      "Stay connected on the go with these touchscreen-friendly gloves.",
      "Conductive material on fingertips for touchscreen compatibility.",
      "Soft and comfortable for all-day wear.",
      "Versatile design suitable for various activities.",
      "Ideal for both casual and formal outfits.",
      "Discounted price for a limited time!",
      "Available in multiple sizes for a perfect fit.",
      "Order now and stay digitally connected!",
      "A thoughtful gift for tech enthusiasts.",
      "Experience digital harmony – get your gloves today!",
    ],
  },
];

export { tempReviewsData, tempProductsData };
